### ISSUE TITLE
Dynamic update data for chart in canvas

### ISSUE THREAD

**Issue by pnbao** [yassipad/chart-js-fabric#4]
Hello, thank you for your great work.
I am able to connect fabric.js with chart.js by using your library. The chart is rendered pretty smooth.
Now I want to update the chart's data dynamically by user input, but the chart is not re-rendered again.
I have checked the chart's `chart` property and can see that all the data are updated correctly, but for some reason it is not displayed in the canvas.

Here is the function I am using for update data.  Is there anything missed, thank you for your help 😄 

```
updateChartData: function(dataset, labels){
    const canvas = CommonHandlers.getCanvas();
    const currentChart = canvas.getActiveObject();
    if (currentChart) {
      currentChart.set('chart', {
        data: {
          labels: labels,
          datasets: dataset.map(row => ({
            label: '# of Votes',
            data: row.map(item => parseFloat(item.value)),
            backgroundColor: [
              'rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)'
            ],
            borderColor: [
              'rgba(255, 99, 132, 1)',
              'rgba(54, 162, 235, 1)',
              'rgba(255, 206, 86, 1)'
            ],
            borderWidth: 1
          })),
        }
      });
    }
    canvas.renderAll();
  }
 ```

**Comment by yassilah** [comment]
Hi! Glad you like the package. Can you simply try to add a `currentChart.set('dirty', true)` after setting the data? The package does not force a re-render after updating the data unless you specifically request it.

**Comment by pnbao** [comment]
Hi @yassipad 😄 
I have tried to set the `dirty` property to true after setting the data but the chart is not auto-update until I drag it. And by setting the `dirty` property, I cannot interact with the chart as before (hover to see the value, ...).

**Comment by pnbao** [comment]
Hi @yassipad,
Thank you for your tip 🤩  It can render new data smoothly now 👍🏻 
By the way, I also have faced a problem with chart scaling.

When I try to scale the chart, it sometimes renders a blank object. I think it relates to the `responsive` and `maintainAspectRatio` options, I have to set these options to true but not working properly. Do you have any idea? 😄 

![Screen Recording 2021-03-31 at 11 13 58](https://user-images.githubusercontent.com/11147999/113081808-5485fb00-9214-11eb-96cb-a8adcb39dc29.gif)

**Comment by yassilah** [comment]
This is a bit odd but unfortunately i think it's probably related to the number of rendering requests when scaling... Is cache disabled ?

**Comment by pnbao** [comment]
I have set the `objectCaching: true` when creating the chart but still face the same problem.

**Comment by QJesus** [comment]
``` diff
public initialize(options?: fabric.IChartConfiguration) {
	super.initialize(options);
	this.__createChart();
	this.__bindChartEvents();

	this.on('scaling', debounce(this.__setChartSize.bind(this), 5));
+	this.on('scaled', _ => {
+		const config = {
+			width: Math.ceil(this.width * this.scaleX),
+			height: Math.ceil(this.height * this.scaleY),
+			scaleX: 1.0,
+			scaleY: 1.0,
+		};
+		Object.keys(config).forEach(k => this.set.apply(this, [k, config[k]]), this);
+		this.__setChartSize.bind(this);
+	});

	return this
}
```

**Comment by pnbao** [comment]
Thank you @QJesus,  it works amazingly! 😄

**Comment by mshameer237** [comment]
@QJesus @pnbao Hi, Can you tell me what exactly the above code by @QJesus does? I am facing the same blank object issue on scaling.

**Comment by QJesus** [comment]
after scaled, resize width, height and scaleX/Y equals 1, chat cannot be scaled

can change `Object.keys(config).forEach(k => this.set.apply(this, [k, config[k]]), this);` to `this.set(config)`
